---
title: Cat Lover
author: ''
date: '2022-03-04'
slug: cat-lover
categories: []
tags: []
---

## Preliminary

```{r}
library(tidyverse)
```

## Import GitHub
```{r}
url <- 'https://raw.githubusercontent.com/BryanAviles-Lopez/tidyverse/main/cat-lovers.csv'
cat_lovers <- read_csv(url)
names(cat_lovers)
url <- 'https://raw.githubusercontent.com/BryanAviles-Lopez/tidyverse/main/hotels.csv'
hotels <- read_csv(url)
names(hotels)
```
## Looking at the data
```{r}
glimpse(cat_lovers)
```

## Computing the mean
```{r}
cat_lovers %>%
  mutate(number_of_cats = case_when(
    name == "Ginger Clark" ~ 2,
    name == "Doug Bass"    ~ 3,
    TRUE                   ~ as.numeric(number_of_cats)
    )) %>%
  summarise(mean_cats = mean(number_of_cats))
```
## Fixing up the data
```{r}
cat_lovers <- cat_lovers %>%
  mutate(
    number_of_cats = case_when(
      name == "Ginger Clark" ~ "2",
      name == "Doug Bass"    ~ "3",
      TRUE                   ~ number_of_cats
      ),
    number_of_cats = as.numeric(number_of_cats)
    )
```

## Examples of using the typeof function
```{r}
typeof(1)
typeof("a")
typeof(c(1, "a"))
```

## Plots
```{r}
ggplot(cat_lovers, mapping = aes(x = handedness)) +
  geom_bar()
```

```{r}
cat_lovers %>%
  mutate(handedness = fct_infreq(handedness)) %>%
  ggplot(mapping = aes(x = handedness)) +
  geom_bar()
```
## Plotting the arrival dates into hotels
```{r}
hotels %>%
  select(starts_with("arrival_"))
```

```{r}
library(glue)
hotels %>%
  mutate(
    arrival_date = glue("{arrival_date_year} {arrival_date_month} {arrival_date_day_of_month}")
    ) %>% 
  relocate(arrival_date)
```

```{r}
hotels %>%
  mutate(arrival_date = glue("{arrival_date_year} {arrival_date_month} {arrival_date_day_of_month}")) %>%
  count(arrival_date)
```

```{r}
hotels %>%
  mutate(arrival_date = glue("{arrival_date_year} {arrival_date_month} {arrival_date_day_of_month}")) %>%
  count(arrival_date) %>%
  ggplot(aes(x = arrival_date, y = n, group = 1)) +
  geom_line()
```


```{r}
library(lubridate)
hotels %>%
  mutate(
    arrival_date = ymd(glue("{arrival_date_year} {arrival_date_month} {arrival_date_day_of_month}"))
    ) %>% 
  relocate(arrival_date)
```

```{r}
hotels %>%
  mutate(arrival_date = ymd(glue("{arrival_date_year} {arrival_date_month} {arrival_date_day_of_month}"))) %>% 
  count(arrival_date)
```
## Plot of arrival date

## Crazy looking plot
```{r}
hotels %>%
  mutate(arrival_date = ymd(glue("{arrival_date_year} {arrival_date_month} {arrival_date_day_of_month}"))) %>% 
  count(arrival_date) %>%
  ggplot(aes(x = arrival_date, y = n, group = 1)) +
  geom_line()
```
## Pretty plot
```{r}
hotels %>%
  mutate(arrival_date = ymd(glue("{arrival_date_year} {arrival_date_month} {arrival_date_day_of_month}"))) %>% 
  count(arrival_date) %>%
  ggplot(aes(x = arrival_date, y = n, group = 1)) +
  geom_smooth()
```

